### ISSUE TITLE
Pressing "Clear Markers" button a lot of times slows program

### ISSUE THREAD

**Issue by kl0211** [PSU-Capstone-2014-B/routelandia-android#22]
After several presses, the program lags. Each map is overlayed on top of the other and pressing back just goes back to the previous map.

**Comment by locdle** [comment]
yes, after pressing clear marker button, the app does the request to download json, and parse that json to get the list of latlng.

If they do more times, it should slow the phone as expected

**Comment by kl0211** [comment]
Re-opening this because the issue is still present. I would suggest changing the app so that the clear button deletes the current map and then creates a new one. Or at least block the button until the user places the two markers on the map.

**Comment by locdle** [comment]
users need to drag one or two markers so they can click the clear button

**Comment by locdle** [comment]
Problem has been solved
