### ISSUE TITLE
Handling response codes 

### ISSUE THREAD

**Issue by donahue2** [PSU-Capstone-2014-B/routelandia-android#50]
Currently, if there is an error and the beck end sends a non-200 response code, the app does not handle it.

The app needs to handle these errors gracefully.

400-series code: can display error code in error object
500-series code: shouldn't display error code

**Comment by donahue2** [comment]
Hmm, I'm having a little trouble finding exactly where we're letting an error slip through in the code.

**Comment by kl0211** [comment]
@donahue2: Take a look at the file HttpAsyncTask.java. On line 113, there is an execution of the post. httpResponse will then have the response from the server. If you look at http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/HttpClient.html, you can see some methods for extracting the response code.

Hope this helps.

**Comment by donahue2** [comment]
There we go, that's what I was needing. Thanks!

**Comment by joshproehl** [comment]
PR gives the base code for this, but there may be other places where the result needs to be caught or error messages need to be displayed!

ALSO, it would be really nice to log the "error" that is in the JSON object whenever one of these occurs, to make debugging easier!
