### ISSUE TITLE
Date chooser should default day-of-week to today's day

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-android#60]
If it is a thursday, the default date shown in the statistics date chooser should be thursday. :-)

**Comment by teslajoy** [comment]
made a pull request on possible fix

**Comment by joshproehl** [comment]
There isn't an open PR for this, did it get merged? (Not seing the app default to today's date)

**Comment by locdle** [comment]
the default day is Sunday if users don't tchoose day
